# This script is used to mine blocks to a specific address every 2 seconds. 
# That address is generated by the script itself.

import os
import time
import subprocess

# Define RPC credentials
rpc_user = "bitcoinuser"
rpc_password = "bitcoinpassword"

# Function to get a new address
def get_new_address():
    try:
        address = subprocess.check_output(
            f"bitcoin-cli -rpcuser={rpc_user} -rpcpassword={rpc_password} getnewaddress",
            shell=True,
            text=True
        ).strip()
        return address
    except Exception as e:
        print(f"Error generating address: {e}")
        return None

# Get an initial valid address
address = get_new_address()
if not address:
    print("Failed to generate a valid address. Exiting.")
    exit(1)

# Generate the required 100 blocks first then
# Run the command every 2 seconds
try:
    command = f"bitcoin-cli -rpcuser={rpc_user} -rpcpassword={rpc_password} generatetoaddress 101 {address}"
    while True:
        command = f"bitcoin-cli -rpcuser={rpc_user} -rpcpassword={rpc_password} generatetoaddress 1 {address}"
        os.system(command)
        print("Command executed successfully.")
        time.sleep(2)  # Wait for 2 seconds
except KeyboardInterrupt:
    print("\nProcess interrupted by user. Exiting...")
