# This script is used to mine blocks to a specific address every 2 seconds.
# That address is generated by the script itself.

import time
import sys
import subprocess

BITCOIN_CLI = ''

# Function to get a new address
def get_new_address(user, password):
    try:
        address = subprocess.check_output(
            f"{BITCOIN_CLI} -rpcuser={user} -rpcpassword={password} getnewaddress",
            shell=True,
            text=True
        ).strip()
        return address
    except Exception as e:
        print(f"Error generating address: {e}")
        return None

def main(user, password):
    if BITCOIN_CLI == '':
        print(f'mine_blocks: Path to bitcoin-cli not available. Exiting.')
        return
    # Get an initial valid address
    address = get_new_address(user, password)
    if not address:
        print("Failed to generate a valid address. Exiting.")
        exit(1)

    # Generate the required 100 blocks first then
    # Run the command every 2 seconds
    try:
        from utils.config import cfg
        cfg.load()
        initial_blocks = cfg.INITIAL_MINING_BLOCKS
        regular_blocks = cfg.REGULAR_MINING_BLOCKS

        # Mine the initial batch for coinbase maturity
        init_command = [f"{BITCOIN_CLI}", f"-rpcuser={user}", f"-rpcpassword={password}", "generatetoaddress", f"{initial_blocks}", f"{address}"]
        subprocess.run(init_command, stdout=subprocess.DEVNULL)

        while True:
            command = [f"{BITCOIN_CLI}", f"-rpcuser={user}", f"-rpcpassword={password}", "generatetoaddress", f"{regular_blocks}", f"{address}"]
            subprocess.run(command, stdout=subprocess.DEVNULL)
            time.sleep(2)
    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Exiting...")

if __name__ == "__main__":
    if len(sys.argv) > 3:
        BITCOIN_CLI = sys.argv[3]
        main(sys.argv[1], sys.argv[2])
    elif len(sys.argv) > 2:
        print(f'mine_blocks: No path to bitcoin-cli given. Attempting to load from config.env')
        try:
            from utils.config import cfg
            cfg.load()
            BITCOIN_CLI = cfg.BITCOIN_CLI
            print(f'mine_blocks: Loading success. Starting bitcoin miner')
            main(sys.argv[1], sys.argv[2])
        except Exception as e:
            print(f'mine_blocks: ERROR: {e}')
    else:
        print(f'mine_blocks: ERROR: Not enough arguments. Please provide an rpc username and password for bitcoin-core')
