# This script is used to mine blocks to a specific address every 2 seconds. 
# That address is generated by the script itself.

import time
import sys
import subprocess
from dotenv import load_dotenv

BITCOIN_CLI = ''

# Function to get a new address
def get_new_address(user, password):
    try:
        address = subprocess.check_output(
            f"{BITCOIN_CLI} -rpcuser={user} -rpcpassword={password} getnewaddress",
            shell=True,
            text=True
        ).strip()
        return address
    except Exception as e:
        print(f"Error generating address: {e}")
        return None

def main(user, password):
    if BITCOIN_CLI == '':
        print(f'mineBlocks: Path to bitcoin-cli not available. Exiting.')
    # Get an initial valid address
    address = get_new_address(user, password)
    if not address:
        print("Failed to generate a valid address. Exiting.")
        exit(1)

    # Generate the required 100 blocks first then
    # Run the command every 2 seconds
    try:
        command = [f"{BITCOIN_CLI}", f"-rpcuser={user}", f"-rpcpassword={password}", "generatetoaddress", "201", f"{address}"]
        while True:        
            command = [f"{BITCOIN_CLI}", f"-rpcuser={user}", f"-rpcpassword={password}", "generatetoaddress", "10", f"{address}"]
            subprocess.run(command, stdout=subprocess.DEVNULL)
            # print("Command executed successfully.")
            time.sleep(2)
    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Exiting...")

if __name__ == "__main__":
    if len(sys.argv) > 3:
        BITCOIN_CLI = sys.argv[3]
        main(sys.argv[1], sys.argv[2])
    if len(sys.argv) > 2:
        print(f'mineBlocks: No path to bitcoin-cli given. attempting to load from config.env')
        try:
            import os
            from dotenv import load_dotenv
            load_dotenv('config.env')
            BITCOIN_CLI = os.getenv('BITCOIND_PATH')
            print(f'mineBlocks: Loading success. Starting bitcoin miner')
            main(sys.argv[1], sys.argv[2])
        except Exception as  e:
            print(f'mineBlocks: ERROR: {e}')
    else:
        print(f'mineBlocks: ERROR: Not enough arguments. Please provide an rpc username and password for bitcoin-core')
