# This script is used to mine blocks to a specific address every 2 seconds. 
# That address is generated by the script itself.

import time
import sys
import subprocess

# Function to get a new address
def get_new_address(user, password):
    try:
        address = subprocess.check_output(
            f"bitcoin-cli -rpcuser={user} -rpcpassword={password} getnewaddress",
            shell=True,
            text=True
        ).strip()
        return address
    except Exception as e:
        print(f"Error generating address: {e}")
        return None

def main(user, password):
    # Get an initial valid address
    address = get_new_address(user, password)
    if not address:
        print("Failed to generate a valid address. Exiting.")
        exit(1)

    # Generate the required 100 blocks first then
    # Run the command every 2 seconds
    try:
        command = [f"bitcoin-cli", f"-rpcuser={user}", f"-rpcpassword={password}", "generatetoaddress", "201", f"{address}"]
        while True:        
            command = [f"bitcoin-cli", f"-rpcuser={user}", f"-rpcpassword={password}", "generatetoaddress", "12", f"{address}"]
            subprocess.run(command, stdout=subprocess.DEVNULL)
            # print("Command executed successfully.")
            time.sleep(5)  # Wait for 2 seconds
    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Exiting...")

if __name__ == "__main__":
    if len(sys.argv) > 2:
        main(sys.argv[1], sys.argv[2])
    else:
        print(f'mineBlocks: ERROR: Not enough arguments. Please provide an rpc username and password for bitcoin-core')
